// webclient2/src/components/app/components/Topbar.vue
<template lang="pug">
.bar
  .container
    .inner
      img.logo(src="../../../assets/logo.svg")
      button.button.is-outlined.is-danger(
        @click="logout" :class=`{"is-loading": loadingUser}`) Logout
</template>

<script lang="ts">
import Vue from "vue";
import { PropValidator } from "vue/types/options";

export default Vue.extend({
  props: {
    loadingUser: Boolean,
    logout: Function as PropValidator<() => void>
  }
});
</script>

<style lang="sass" scoped>
.bar
  background: white
  border-bottom: 1px solid #d0e0ff

.inner
  padding: 1rem
  display: grid
  grid-template-columns: 1fr auto

.logo
  height: 40px
</style>

// webclient3/src/pages/home/components/Topbar.tsx
import { observer } from "mobx-react";
import React from "react";
import styled from "styled-components";
import { ReactComponent as Logo } from "../../../assets/logo.svg";

type Props = {
  loggedIn: boolean;
  loading: boolean;
  toggleLogin: () => void;
  logout: () => void;
};

export default observer((props: Props) => {
  return (
    <SBar>
      <div className="container">
        <div className="level">
          <div className="level-left">
            <div className="level-item">
              <Logo height="50px" width={undefined} />
            </div>
          </div>
          <div className="level-right">
            <div className="level-item">
              <div className="buttons has-addons">
                {props.loggedIn ? (
                  <>
                    <button className="button">Go to app</button>
                    <button className="button" onClick={props.logout}>
                      Logout
                    </button>
                  </>
                ) : !props.loading ? (
                  <button className="button" onClick={props.toggleLogin}>
                    Login
                  </button>
                ) : (
                  <button className="button is-loading">Loading</button>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </SBar>
  );
});

const SBar = styled.div`
  background: white;
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #e1e1e1;
`;
