// webclient2/src/components/viewcards/components/Cards.vue
<template lang="pug">
.cards
  .box(v-for="card in cards")
    b {{card.title}}
    p {{card.text}}
    .cardTags(v-if="card.tags.length > 0")
      .cardTag(
        v-for="tag in card.tags"
        v-if="tag"
        :style=`{background: tag.color}`) {{tag.text}}
</template>

<script lang="ts">
import Vue from "vue";
import { PropValidator } from "vue/types/options";

export default Vue.extend({
  props: {
    cards: Array as PropValidator<
      {
        cardID: string;
        title: string;
        text: string;
        tags: { tagID: string; text: string; color: string }[];
      }[]
    >
  }
});
</script>

<style lang="sass" scoped>
.cards
  margin-top: 1rem
  display: grid
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr))
  grid-gap: 1rem

.box
  margin-bottom: 0

.cardTags
  display: grid
  grid-auto-flow: column
  grid-gap: .3rem
  justify-content: start
  margin-top: .5rem

  .cardTag
    font-size: .7rem
    padding: 0 .3rem
    border-radius: .3rem
    color: black
</style>

// webclient/src/Components/Cards.tsx
import React from "react";
import styled from "styled-components";
import { Card, Tag } from "../Store/Model";
import { SBox, SBoxBody, SBoxTitle } from "../ui";

export const Cards = ({ cards, tags }: { cards: Card[]; tags: Tag[] }) => {
  const allTagIDs = tags.map(tag => tag.tagID);

  const tagsOfCard = (card: Card): Tag[] =>
    card.tagIDs.map(tagID => tags[allTagIDs.indexOf(tagID)]);

  return (
    <SContainer>
      {cards.map(card => (
        <SBox key={card.cardID}>
          <SBoxTitle>{card.title}</SBoxTitle>
          <SBoxBody>{card.text}</SBoxBody>
          {card.tagIDs.length > 0 && (
            <STags>
              {tagsOfCard(card).map(tag => (
                <STag key={tag.tagID} color={tag.color}>
                  {tag.name}
                </STag>
              ))}
            </STags>
          )}
        </SBox>
      ))}
    </SContainer>
  );
};

const SContainer = styled.div`
  display: grid;
  grid-gap: 1rem;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
`;

const STags = styled.div`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  grid-gap: 0.5rem;
  padding-top: 0.5rem;

  font-size: 0.7rem;
`;

const STag = styled.div<{ color: string }>`
  padding: 0.2rem 0.5rem;

  background: ${p => p.color};
  border-radius: 0.2rem;
`;
