// webclient/src/Components/NavBar.tsx
import React from "react";
import { Link } from "react-router-dom";
import styled from "styled-components";
import { SPageCenter, SVertBar } from "../ui";

export const NavBar = ({ path }: { path: string }) => (
  <SVertBar>
    <SPageCenter>
      <SBarButtons>
        <SBarButton to="/" selected={path === ""}>
          View cards
        </SBarButton>
        <SBarButton to="/learn" selected={path === "learn"}>
          Learn
        </SBarButton>
      </SBarButtons>
    </SPageCenter>
  </SVertBar>
);

const SBarButtons = styled.div`
  display: flex;
  flex-direction: row;

  padding: 0 0.5rem;
`;

const SBarButton = styled(Link)<{ selected?: boolean }>`
  :not(:first-child) {
    margin-left: 2rem;
  }

  :hover {
    color: #444;
    border-bottom-color: #444;
  }

  :focus {
    outline: none;
  }

  padding: 0.7rem 0;
  border-bottom: 1px solid transparent;
  transition: 0.2s border-bottom-color;
  cursor: pointer;
  text-decoration: none;
  color: inherit;

  ${p =>
    p.selected &&
    `
    &, :hover {
      color: #5050ff;
      border-bottom-color: #5050ff;
    }
  `}
`;

// webclient2/src/components/app/components/Navbar.vue
<template lang="pug">
.bar
  .container
    .inner
      router-link(
        v-for="route in routes"
        :key="route[0]"
        :class=`{"selected": route[4]}`
        :to="route[0]")
        span.icon
          i.fas(:class="route[3]")
        | {{route[1]}}
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    routes: Array
  }
});
</script>

<style lang="sass" scoped>
.bar
  background: white
  border-bottom: 1px solid #d0e0ff

.inner
  padding: 0 1rem

a
  display: inline-block
  padding: .75rem 1rem
  color: #a8a8a8
  border-bottom: 1px solid transparent
  transition: .1s border-bottom-color, .1s color

  span
    margin-right: .3rem

  &:focus
    outline: none

  &:hover
    color: blue
    border-bottom-color: blue

  &.selected, &.selected:hover
    color: black
    border-bottom-color: black
</style>
