// webclient/src/shared/components/Topbar.tsx
import { observer } from "mobx-react";
import React from "react";
import styled from "styled-components";
import { ReactComponent as Logo } from "../../assets/logo.svg";

type Props = { children: JSX.Element };

export default observer((props: Props) => {
  return (
    <SBar>
      <div className="container">
        <SContainer>
          <Logo height="40px" width={undefined} />
          <div>{props.children}</div>
        </SContainer>
      </div>
    </SBar>
  );
});

const SBar = styled.div`
  background: white;
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #e1e1e1;
`;

const SContainer = styled.div`
  display: flex;
  justify-content: space-between;
`;

// webclient2/src/components/app/components/Topbar.vue
<template lang="pug">
.bar
  .container
    .inner
      img.logo(src="../../../assets/logo.svg")
      button.button.is-outlined.is-danger(
        @click="logout" :class=`{"is-loading": loadingUser}`) Logout
</template>

<script lang="ts">
import Vue from "vue";
import { PropValidator } from "vue/types/options";

export default Vue.extend({
  props: {
    loadingUser: Boolean,
    logout: Function as PropValidator<() => void>
  }
});
</script>

<style lang="sass" scoped>
.bar
  background: white
  border-bottom: 1px solid #d0e0ff

.inner
  padding: 1rem
  display: flex
  justify-content: space-between
  flex-wrap: wrap

.logo
  height: 40px
</style>
