// webclient2/src/components/app/components/Navbar.vue
<template lang="pug">
.bar
  .container
    .inner
      router-link(
        v-for="route in routes"
        :key="route[0]"
        :class=`{"selected": route[4]}`
        :to="route[0]")
        span.icon
          i.fas(:class="route[3]")
        | {{route[1]}}
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    routes: Array
  }
});
</script>

<style lang="sass" scoped>
.bar
  background: white
  border-bottom: 1px solid #d0e0ff

.inner
  padding: 0 1rem

a
  display: inline-block
  padding: .75rem 1rem
  color: #a8a8a8
  border-bottom: 1px solid transparent
  transition: .1s border-bottom-color, .1s color

  span
    margin-right: .3rem

  &:focus
    outline: none

  &:hover
    color: blue
    border-bottom-color: blue

  &.selected, &.selected:hover
    color: black
    border-bottom-color: black
</style>

// webclient/src/pages/app/components/Navbar.tsx
import { observer } from "mobx-react";
import React from "react";
import { Link } from "react-router-dom";
import styled from "styled-components";

type Props = {
  routes: { text: string; icon: string; route: string }[];
  currRoute: string;
};

export default observer((props: Props) => {
  return (
    <SBar>
      <div className="container">
        {props.routes.map(route => (
          <SLink
            key={route.route}
            className={route.route === props.currRoute ? "selected" : ""}
            to={route.route}
          >
            <span className="icon">
              <i className={route.icon} />
            </span>
            {route.text}
          </SLink>
        ))}
      </div>
    </SBar>
  );
});

const SBar = styled.div`
  background: white;
  padding: 0rem 1rem;
  border-bottom: 1px solid #e1e1e1;
`;

const SLink = styled(Link)`
  display: inline-block;
  padding: 0.8rem 1rem;
  color: #919191;
  border-bottom: 1px solid transparent;
  transition: 0.1s color, 0.1s border-bottom-color;

  span {
    margin-right: 0.5rem;
  }

  &.selected {
    color: black;
    border-bottom-color: black;
  }

  :not(.selected):hover {
    color: #3769ff;
    border-bottom-color: #3769ff;
  }

  :focus {
    outline: none;
  }
`;
